-- MySQL Script generated by MySQL Workbench
-- jue 24 abr 2025 11:00:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ClubDeportivoLaSalle
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ClubDeportivoLaSalle` ;

-- -----------------------------------------------------
-- Schema ClubDeportivoLaSalle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ClubDeportivoLaSalle` ;
USE `ClubDeportivoLaSalle` ;

-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`users` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `role` ENUM('admin', 'coach', 'player', 'member') NOT NULL,
  `in_date` DATE NOT NULL,
  `update_date` DATETIME NULL,
  `out_date` DATE NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`seasons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`seasons` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`seasons` (
  `season_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`season_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`teams` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`teams` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `season_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `category` ENUM('premini', 'mini', 'youth', 'cadet', 'junior', 'senior') NOT NULL,
  `gender` ENUM('female', 'male', 'mixed') NOT NULL,
  `is_active` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `fk_teams_seasons1_idx` (`season_id` ASC) VISIBLE,
  CONSTRAINT `fk_teams_seasons1`
    FOREIGN KEY (`season_id`)
    REFERENCES `ClubDeportivoLaSalle`.`seasons` (`season_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`players` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`players` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  `gender` ENUM('female', 'male') NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname1` VARCHAR(45) NOT NULL,
  `surname2` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `position` ENUM('point guard', 'shooting guard', 'small forward', 'power forward', 'center') NOT NULL,
  `height` INT UNSIGNED NOT NULL,
  `hand` ENUM('left-handed', 'right-handed') NOT NULL,
  PRIMARY KEY (`player_id`),
  INDEX `fk_players_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_players_teams1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_players_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ClubDeportivoLaSalle`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `ClubDeportivoLaSalle`.`teams` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`coaches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`coaches` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`coaches` (
  `coach_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  `gender` ENUM('female', 'male', 'other') NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname1` VARCHAR(45) NOT NULL,
  `surname2` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `title` ENUM('none', 'made', 'level 1', 'level 2', 'level 3') NOT NULL,
  PRIMARY KEY (`coach_id`),
  INDEX `fk_coaches_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_coaches_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ClubDeportivoLaSalle`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`member` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`member` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `family` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `fk_member_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ClubDeportivoLaSalle`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`rivals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`rivals` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`rivals` (
  `rival_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rival_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`matches` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`matches` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `season_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `rival_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `home_or_away` ENUM('home', 'away') NOT NULL,
  `home_score` INT UNSIGNED NULL,
  `away_score` INT UNSIGNED NULL,
  `general_comment` TEXT NULL,
  PRIMARY KEY (`match_id`),
  INDEX `fk_matches_teams1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_matches_rivals1_idx` (`rival_id` ASC) VISIBLE,
  INDEX `fk_matches_seasons1_idx` (`season_id` ASC) VISIBLE,
  CONSTRAINT `fk_matches_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `ClubDeportivoLaSalle`.`teams` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_rivals1`
    FOREIGN KEY (`rival_id`)
    REFERENCES `ClubDeportivoLaSalle`.`rivals` (`rival_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_seasons1`
    FOREIGN KEY (`season_id`)
    REFERENCES `ClubDeportivoLaSalle`.`seasons` (`season_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`coaches_teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`coaches_teams` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`coaches_teams` (
  `coach_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `role` ENUM('head', 'assistant', 'other') NOT NULL,
  PRIMARY KEY (`coach_id`, `team_id`),
  INDEX `fk_coaches_has_teams_teams1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_coaches_has_teams_coaches1_idx` (`coach_id` ASC) VISIBLE,
  CONSTRAINT `fk_coaches_has_teams_coaches1`
    FOREIGN KEY (`coach_id`)
    REFERENCES `ClubDeportivoLaSalle`.`coaches` (`coach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coaches_has_teams_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `ClubDeportivoLaSalle`.`teams` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClubDeportivoLaSalle`.`matches_feedbacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClubDeportivoLaSalle`.`matches_feedbacks` ;

CREATE TABLE IF NOT EXISTS `ClubDeportivoLaSalle`.`matches_feedbacks` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `match_id` INT NOT NULL,
  `coach_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `fk_table1_coaches1_idx` (`coach_id` ASC) VISIBLE,
  INDEX `fk_table1_players1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_table1_matches1_idx` (`match_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_coaches1`
    FOREIGN KEY (`coach_id`)
    REFERENCES `ClubDeportivoLaSalle`.`coaches` (`coach_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `ClubDeportivoLaSalle`.`players` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_matches1`
    FOREIGN KEY (`match_id`)
    REFERENCES `ClubDeportivoLaSalle`.`matches` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
