const players = [
    {
      "player_id": 1,
      "user_id": 5,
      "team_id": 1,
      "nif": "50000001E",
      "gender": "female",
      "name": "MarÃ­a",
      "surname1": "LÃ³pez",
      "surname2": "GarcÃ­a",
      "birthdate": "2000-01-15",
      "phone": "610111111",
      "address": "Calle Mayor 1, Madrid",
      "position": "point guard",
      "height": 175,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 2,
      "user_id": 6,
      "team_id": 1,
      "nif": "50000002F",
      "gender": "female",
      "name": "Carmen",
      "surname1": "MartÃ­nez",
      "surname2": "SÃ¡nchez",
      "birthdate": "2001-02-20",
      "phone": "610222222",
      "address": "Avenida Central 2, Madrid",
      "position": "shooting guard",
      "height": 178,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 3,
      "user_id": 7,
      "team_id": 1,
      "nif": "50000003G",
      "gender": "female",
      "name": "LucÃ­a",
      "surname1": "FernÃ¡ndez",
      "surname2": "MartÃ­n",
      "birthdate": "2000-03-25",
      "phone": "610333333",
      "address": "Plaza EspaÃ±a 3, Madrid",
      "position": "small forward",
      "height": 182,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 4,
      "user_id": 8,
      "team_id": 1,
      "nif": "50000004H",
      "gender": "female",
      "name": "Elena",
      "surname1": "GarcÃ­a",
      "surname2": "RodrÃ­guez",
      "birthdate": "2001-04-10",
      "phone": "610444444",
      "address": "Calle Sol 4, Madrid",
      "position": "power forward",
      "height": 185,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 5,
      "user_id": 9,
      "team_id": 1,
      "nif": "50000005I",
      "gender": "female",
      "name": "Paula",
      "surname1": "PÃ©rez",
      "surname2": "GonzÃ¡lez",
      "birthdate": "2000-05-05",
      "phone": "610555555",
      "address": "Avenida Luna 5, Madrid",
      "position": "center",
      "height": 190,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 6,
      "user_id": 10,
      "team_id": 1,
      "nif": "50000006J",
      "gender": "female",
      "name": "SofÃ­a",
      "surname1": "GÃ³mez",
      "surname2": "DÃ­az",
      "birthdate": "2001-06-15",
      "phone": "610666666",
      "address": "Calle Estrella 6, Madrid",
      "position": "shooting guard",
      "height": 176,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 7,
      "user_id": 11,
      "team_id": 1,
      "nif": "50000007K",
      "gender": "female",
      "name": "Alba",
      "surname1": "SÃ¡nchez",
      "surname2": "Ãlvarez",
      "birthdate": "2000-07-20",
      "phone": "610777777",
      "address": "Avenida Mar 7, Madrid",
      "position": "point guard",
      "height": 173,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 8,
      "user_id": 12,
      "team_id": 2,
      "nif": "50000008L",
      "gender": "female",
      "name": "Marta",
      "surname1": "Romero",
      "surname2": "Moreno",
      "birthdate": "2005-08-12",
      "phone": "610888888",
      "address": "Calle Alta 8, Madrid",
      "position": "center",
      "height": 183,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 9,
      "user_id": 13,
      "team_id": 2,
      "nif": "50000009M",
      "gender": "female",
      "name": "Sara",
      "surname1": "Navarro",
      "surname2": "Ruiz",
      "birthdate": "2006-09-18",
      "phone": "610999999",
      "address": "Avenida Baja 9, Madrid",
      "position": "power forward",
      "height": 180,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 10,
      "user_id": 14,
      "team_id": 2,
      "nif": "50000010N",
      "gender": "female",
      "name": "Julia",
      "surname1": "Torres",
      "surname2": "Castro",
      "birthdate": "2005-10-23",
      "phone": "611000000",
      "address": "Plaza Mayor 10, Madrid",
      "position": "small forward",
      "height": 176,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 11,
      "user_id": 15,
      "team_id": 2,
      "nif": "50000011O",
      "gender": "female",
      "name": "Andrea",
      "surname1": "Ortega",
      "surname2": "Flores",
      "birthdate": "2006-11-05",
      "phone": "611111111",
      "address": "Calle Ancha 11, Madrid",
      "position": "shooting guard",
      "height": 172,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 12,
      "user_id": 16,
      "team_id": 2,
      "nif": "50000012P",
      "gender": "female",
      "name": "Claudia",
      "surname1": "Molina",
      "surname2": "Serrano",
      "birthdate": "2005-12-15",
      "phone": "611222222",
      "address": "Avenida Larga 12, Madrid",
      "position": "point guard",
      "height": 170,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 13,
      "user_id": 17,
      "team_id": 2,
      "nif": "50000013Q",
      "gender": "female",
      "name": "Laura",
      "surname1": "Delgado",
      "surname2": "Ramos",
      "birthdate": "2006-01-25",
      "phone": "611333333",
      "address": "Calle Norte 13, Madrid",
      "position": "center",
      "height": 182,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 14,
      "user_id": 18,
      "team_id": 2,
      "nif": "50000014R",
      "gender": "female",
      "name": "Cristina",
      "surname1": "Ortiz",
      "surname2": "Medina",
      "birthdate": "2005-02-14",
      "phone": "611444444",
      "address": "Avenida Sur 14, Madrid",
      "position": "power forward",
      "height": 178,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 15,
      "user_id": 19,
      "team_id": 3,
      "nif": "50000015S",
      "gender": "female",
      "name": "Nuria",
      "surname1": "Reyes",
      "surname2": "Guerrero",
      "birthdate": "2007-03-20",
      "phone": "611555555",
      "address": "Plaza Norte 15, Madrid",
      "position": "point guard",
      "height": 165,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 16,
      "user_id": 20,
      "team_id": 3,
      "nif": "50000016T",
      "gender": "female",
      "name": "Patricia",
      "surname1": "Lozano",
      "surname2": "Cano",
      "birthdate": "2008-04-11",
      "phone": "611666666",
      "address": "Calle Este 16, Madrid",
      "position": "shooting guard",
      "height": 168,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 17,
      "user_id": 21,
      "team_id": 3,
      "nif": "50000017U",
      "gender": "female",
      "name": "Raquel",
      "surname1": "Mendoza",
      "surname2": "Prieto",
      "birthdate": "2007-05-22",
      "phone": "611777777",
      "address": "Avenida Oeste 17, Madrid",
      "position": "small forward",
      "height": 172,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 18,
      "user_id": 22,
      "team_id": 3,
      "nif": "50000018V",
      "gender": "female",
      "name": "Marina",
      "surname1": "Cruz",
      "surname2": "Herrera",
      "birthdate": "2008-06-13",
      "phone": "611888888",
      "address": "Calle Sur 18, Madrid",
      "position": "power forward",
      "height": 175,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 19,
      "user_id": 23,
      "team_id": 3,
      "nif": "50000019W",
      "gender": "female",
      "name": "Diana",
      "surname1": "Cabrera",
      "surname2": "MarÃ­n",
      "birthdate": "2007-07-24",
      "phone": "611999999",
      "address": "Avenida Este 19, Madrid",
      "position": "center",
      "height": 180,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 20,
      "user_id": 24,
      "team_id": 3,
      "nif": "50000020X",
      "gender": "female",
      "name": "Irene",
      "surname1": "SÃ¡ez",
      "surname2": "Vega",
      "birthdate": "2008-08-15",
      "phone": "612000000",
      "address": "Plaza Oeste 20, Madrid",
      "position": "small forward",
      "height": 173,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 21,
      "user_id": 25,
      "team_id": 3,
      "nif": "50000021Y",
      "gender": "female",
      "name": "Lorena",
      "surname1": "Rubio",
      "surname2": "RomÃ¡n",
      "birthdate": "2007-09-26",
      "phone": "612111111",
      "address": "Calle Centro 21, Madrid",
      "position": "point guard",
      "height": 168,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 22,
      "user_id": 26,
      "team_id": 4,
      "nif": "50000022Z",
      "gender": "male",
      "name": "Daniel",
      "surname1": "JimÃ©nez",
      "surname2": "MuÃ±oz",
      "birthdate": "2000-10-10",
      "phone": "612222222",
      "address": "Avenida Principal 22, Madrid",
      "position": "center",
      "height": 200,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 23,
      "user_id": 27,
      "team_id": 4,
      "nif": "50000023A",
      "gender": "male",
      "name": "Alejandro",
      "surname1": "Blanco",
      "surname2": "Alonso",
      "birthdate": "2001-11-05",
      "phone": "612333333",
      "address": "Calle Nueva 23, Madrid",
      "position": "power forward",
      "height": 195,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 24,
      "user_id": 28,
      "team_id": 4,
      "nif": "50000024B",
      "gender": "male",
      "name": "Pablo",
      "surname1": "Morales",
      "surname2": "Santos",
      "birthdate": "2000-12-15",
      "phone": "612444444",
      "address": "Plaza Vieja 24, Madrid",
      "position": "small forward",
      "height": 192,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 25,
      "user_id": 29,
      "team_id": 4,
      "nif": "50000025C",
      "gender": "male",
      "name": "Sergio",
      "surname1": "Iglesias",
      "surname2": "Castillo",
      "birthdate": "2001-01-20",
      "phone": "612555555",
      "address": "Calle Antigua 25, Madrid",
      "position": "shooting guard",
      "height": 188,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 26,
      "user_id": 30,
      "team_id": 4,
      "nif": "50000026D",
      "gender": "male",
      "name": "Jorge",
      "surname1": "Hidalgo",
      "surname2": "Cortes",
      "birthdate": "2000-02-25",
      "phone": "612666666",
      "address": "Avenida Moderna 26, Madrid",
      "position": "point guard",
      "height": 185,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 27,
      "user_id": 31,
      "team_id": 4,
      "nif": "50000027E",
      "gender": "male",
      "name": "David",
      "surname1": "Gallego",
      "surname2": "Rojas",
      "birthdate": "2001-03-15",
      "phone": "612777777",
      "address": "Plaza Central 27, Madrid",
      "position": "power forward",
      "height": 196,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 28,
      "user_id": 32,
      "team_id": 4,
      "nif": "50000028F",
      "gender": "male",
      "name": "Javier",
      "surname1": "Bravo",
      "surname2": "Soto",
      "birthdate": "2000-04-18",
      "phone": "612888888",
      "address": "Calle Principal 28, Madrid",
      "position": "center",
      "height": 205,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 29,
      "user_id": 33,
      "team_id": 5,
      "nif": "50000029G",
      "gender": "male",
      "name": "Miguel",
      "surname1": "Pardo",
      "surname2": "SuÃ¡rez",
      "birthdate": "2005-05-12",
      "phone": "612999999",
      "address": "Avenida Alta 29, Madrid",
      "position": "point guard",
      "height": 180,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 30,
      "user_id": 34,
      "team_id": 5,
      "nif": "50000030H",
      "gender": "male",
      "name": "Hugo",
      "surname1": "Vidal",
      "surname2": "Esteban",
      "birthdate": "2006-06-23",
      "phone": "613000000",
      "address": "Calle Baja 30, Madrid",
      "position": "shooting guard",
      "height": 183,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 31,
      "user_id": 35,
      "team_id": 5,
      "nif": "50000031I",
      "gender": "male",
      "name": "AdriÃ¡n",
      "surname1": "Sierra",
      "surname2": "HernÃ¡ndez",
      "birthdate": "2005-07-14",
      "phone": "613111111",
      "address": "Plaza Grande 31, Madrid",
      "position": "small forward",
      "height": 187,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 32,
      "user_id": 36,
      "team_id": 5,
      "nif": "50000032J",
      "gender": "male",
      "name": "Marcos",
      "surname1": "Pastor",
      "surname2": "GutiÃ©rrez",
      "birthdate": "2006-08-25",
      "phone": "613222222",
      "address": "Calle Corta 32, Madrid",
      "position": "power forward",
      "height": 192,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 33,
      "user_id": 37,
      "team_id": 5,
      "nif": "50000033K",
      "gender": "male",
      "name": "Ã“scar",
      "surname1": "Vargas",
      "surname2": "MÃ©ndez",
      "birthdate": "2005-09-16",
      "phone": "613333333",
      "address": "Avenida Larga 33, Madrid",
      "position": "center",
      "height": 198,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 34,
      "user_id": 38,
      "team_id": 5,
      "nif": "50000034L",
      "gender": "male",
      "name": "Alberto",
      "surname1": "LeÃ³n",
      "surname2": "Santiago",
      "birthdate": "2006-10-27",
      "phone": "613444444",
      "address": "Plaza PequeÃ±a 34, Madrid",
      "position": "shooting guard",
      "height": 185,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 35,
      "user_id": 39,
      "team_id": 5,
      "nif": "50000035M",
      "gender": "male",
      "name": "RaÃºl",
      "surname1": "PeÃ±a",
      "surname2": "Fuentes",
      "birthdate": "2005-11-18",
      "phone": "613555555",
      "address": "Calle Estrecha 35, Madrid",
      "position": "small forward",
      "height": 188,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 36,
      "user_id": 40,
      "team_id": 6,
      "nif": "50000036N",
      "gender": "male",
      "name": "RubÃ©n",
      "surname1": "BenÃ­tez",
      "surname2": "Campos",
      "birthdate": "2007-12-19",
      "phone": "613666666",
      "address": "Avenida Ancha 36, Madrid",
      "position": "center",
      "height": 190,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 37,
      "user_id": 41,
      "team_id": 6,
      "nif": "50000037O",
      "gender": "male",
      "name": "Diego",
      "surname1": "Bermejo",
      "surname2": "Vega",
      "birthdate": "2008-01-10",
      "phone": "613777777",
      "address": "Calle Grande 37, Madrid",
      "position": "power forward",
      "height": 185,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 38,
      "user_id": 42,
      "team_id": 6,
      "nif": "50000038P",
      "gender": "male",
      "name": "Mario",
      "surname1": "Carrasco",
      "surname2": "Calvo",
      "birthdate": "2007-02-21",
      "phone": "613888888",
      "address": "Plaza Circular 38, Madrid",
      "position": "small forward",
      "height": 180,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 39,
      "user_id": 43,
      "team_id": 6,
      "nif": "50000039Q",
      "gender": "male",
      "name": "IvÃ¡n",
      "surname1": "Herrero",
      "surname2": "Serra",
      "birthdate": "2008-03-12",
      "phone": "613999999",
      "address": "Calle Redonda 39, Madrid",
      "position": "shooting guard",
      "height": 178,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 40,
      "user_id": 44,
      "team_id": 6,
      "nif": "50000040R",
      "gender": "male",
      "name": "VÃ­ctor",
      "surname1": "Aguilar",
      "surname2": "Pascual",
      "birthdate": "2007-04-23",
      "phone": "614000000",
      "address": "Avenida Recta 40, Madrid",
      "position": "point guard",
      "height": 175,
      "hand": "right-handed",
      "status": "in"
    },
    {
      "player_id": 41,
      "user_id": 45,
      "team_id": 6,
      "nif": "50000041S",
      "gender": "male",
      "name": "Eduardo",
      "surname1": "Soler",
      "surname2": "Nieto",
      "birthdate": "2008-05-14",
      "phone": "614111111",
      "address": "Plaza Cuadrada 41, Madrid",
      "position": "power forward",
      "height": 182,
      "hand": "left-handed",
      "status": "in"
    },
    {
      "player_id": 42,
      "user_id": 46,
      "team_id": 6,
      "nif": "50000042T",
      "gender": "male",
      "name": "Samuel",
      "surname1": "Ferrer",
      "surname2": "Santana",
      "birthdate": "2007-06-25",
      "phone": "614222222",
      "address": "Calle Curva 42, Madrid",
      "position": "center",
      "height": 187,
      "hand": "right-handed",
      "status": "in"
    }
  ];

  export default players;